### ISSUE TITLE
Fragmented scaffolds - large and repetitive genome

### ISSUE THREAD

**Issue by sighe** [theaidenlab/3d-dna#157] opened 2022-10-12 00:44 UTC
Hi. We have got a 3d-dna output using 30x HiFi data and in-house Hi-C for a large, highly repetitive genome of about 5Gb, shown in a contact map on Juicebox like this. 

![image](https://user-images.githubusercontent.com/24567785/195223140-a5a8ee97-909e-486e-a34b-a7d5c6ad1c9d.png)

We see 1) a huge fraction for which we could not retrieve chromatin contact and 2) a number of signals far away from the diagonal line, that is, fragments that failed to be resolved into chromosomal scaffolds. I expect that at least the fractions 2) can be better resolved into chromosomal scaffolds by tweaking with parameters. Any recommendations? 

I would really appreciate your response.

Best regards.

**Comment by dudcha** [comment] 2022-10-12 02:12
Hi,

Closing since this is not a bug report. Please consider reposting in Aidenlab.org/forum.html.

Thanks!
Olga

**Closed as completed by dudcha** 2022-10-12 02:12 UTC
