### ISSUE TITLE
Understanding output

### ISSUE THREAD

**Issue by kkrizanovic** [theaidenlab/3d-dna#134] opened 2021-10-22 14:15 UTC
Hello,

I'm trying to assemble a plant genome of roughly 4Gbp with 11 chromosomes. ATM I'm working on haploid assembly.

I've got about 3000 contings using hifiasm, and after running run-asm-pipeline.py, the FINAL.fasta file contained over 9000 scaffolds. N50 has improved though. I still have to run JBAT post analysis.

I have two questions:
1. Why is the number of scaffolds so much larger than the number of initial contigs?
2. Is there a way to group those scaffolds into chromosomes?

**Comment by dudcha** [comment] 2021-11-11 23:55
Hi kkrizanovic,

I am not sure if I have answered this on the forum or perhaps this was a similar question.

Please take a look at the Genome Assembly Cookbook (dnazoo.org/methods) and many discussions on the forum (aidenlab.org/forum.html) for a general description of the tools and output interpretation. To briefly answer, you want to take a look at the contact maps generated (.0.hic, .final.hic and intermediaries, if necessary).

Hope this helps and closing since this is not a bug,

Olga

**Closed as completed by dudcha** 2021-11-11 23:55 UTC
