### ISSUE TITLE
Use 3d-dna to assist in assembling pacbio hifi data

### ISSUE THREAD

**Issue by xiaobaiymq** [theaidenlab/3d-dna#137] opened 2021-11-26 14:22 UTC
Hello
I used hifiasm to complete the preliminary assembly(no polishing) of pacbio hifi, and then used 3d-dna to anchor the contigs to the chromosome, but the number of chromosomes(n=7) obtained is different from my species(n=9). How should I improve my results?

Thanks

**Comment by dudcha** [comment] 2021-11-28 17:27
Hi xiaobaiymq,

Take a look at the Genome Assembly Cookbook hosted on dnazoo.org/methods. This should give a good overview of the options available within the 3d-dna suite. Also, check out the aidenlab.org/forum.html for a number of discussions on how to read and interpret 3d-dna output.

Closing since this is not a bug. Hope this helps,
Olga

**Closed as completed by dudcha** 2021-11-28 17:27 UTC
