### ISSUE TITLE
deduplicated list of alignments

### ISSUE THREAD

**Issue by Malabady** [theaidenlab/3d-dna#136] opened 2021-11-10 23:35 UTC
Hi,

I am wondering if you have any notes about generating the deduplicated list of alignments of Hi-C reads to the primary assembly fasta file. The help message of run-asm-pipeline.sh is saying "as produced by the Juicer pipeline, but I couldn't find any Juicer tool that does maping and deduplication. Do you have any recommendations about this? 

Another question: if I have an scaffolded assembly using HiRise and generated more data and assembled them. Could I combine the scaffolded assembly with the additional primary assembly in one file and use it as input for the 3d-dna pipeline? 

Thank you!

**Comment by dudcha** [comment] 2021-11-11 23:51
Hi Malabady,

You might want to take a look at the Genome Assembly Cookbook: dnazoo.org/methods. You will find a chapter about Juicer there.

Closing since this is not a bug question. This seems more appropriate for the forum (aidenlab.org/forum.html). Thanks!

Olga

**Closed as completed by dudcha** 2021-11-11 23:51 UTC
