### ISSUE TITLE
Anchor rate is only 75% and how to elevate it

### ISSUE THREAD

**Issue by kuangzhuoran** [theaidenlab/3d-dna#131] opened 2021-09-18 08:09 UTC
Hi ! 

After juicebox, the heatmap is like this:

![d6b1b81b26cd836bfe1e98cc0885151](https://user-images.githubusercontent.com/76553133/133881392-751e1414-7caf-4717-80f8-e1bfdaf57e06.png)
It looks like there are 31 chromosomes
and rerun 3d-DNA, The result is similar, the **bp number of the longest 31 HiC-scaffold/all bp = 0.75**(This is what I call anchor rate)
![6a20d7335a9d730151645d817713604](https://user-images.githubusercontent.com/76553133/133881606-73db94f0-6f6c-4144-8c6d-004904e0b12b.png)

Then, I put 0.hic/assembly file in juicebox,Only some very obvious fragments were moved to debris,So it is like this
![a5a4a0043d9aa5280b7747e45c22ba5](https://user-images.githubusercontent.com/76553133/133881650-68790bd9-2f73-467b-9cc2-4ff51bd9dc6f.png)

Maybe my understanding is wrong，How can I improve my data

Best
Kzr

**Comment by dudcha** [comment] 2021-09-19 04:45
Hi, 

Closing since this is not a bug. If ok with you, this is more appropriate for the forum: aidnelab.org/forum.html.

I would briefly advise to load the coverage track to help see what is going on.

Olga

**Closed as completed by dudcha** 2021-09-19 04:45 UTC
